### ISSUE TITLE
TypeError: Cannot call method 'displayName' of undefined

### ISSUE THREAD

**Issue by nazarhussain** [flemay/less-autoprefixer#4]
After adding this package to my project I am facing this error: 

```
/.meteor/packages/meteor-tool/.1.1.8.6cd09s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot call method 'displayName' of undefined
    at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:141:64)
    at /tools/isobuild/build-plugin.js:171:12
    at Function._.each._.forEach (/home/nazar/.meteor/packages/meteor-tool/.1.1.8.6cd09s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at SourceProcessorSet.merge (/tools/isobuild/build-plugin.js:169:7)
    at /tools/isobuild/compiler.js:368:26
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:364:26
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at compileUnibuild (/tools/isobuild/compiler.js:360:16)
    at /tools/isobuild/compiler.js:175:26
    at Array.forEach (native)
    at Function._.each._.forEach (/.meteor/packages/meteor-tool/.1.1.8.6cd09s++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:171:5)
    at /tools/isobuild/bundler.js:2099:24
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2047:31)
    at /tools/runners/run-app.js:551:36
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at bundleApp (/tools/runners/run-app.js:541:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
```
Can you help me out in solving this issue.

**Comment by micahalcorn** [comment]
Same here with Meteor 1.2.x. :(

**Comment by mason505** [comment]
+ 1

**Comment by flemay** [comment]
@nazarhussain thanks for reporting. I will need to update it for meteor 1.2. :)

**Comment by mason505** [comment]
Thank you for all your work! 

I don’t know if this is helpful or not (and this is antidotal), it seemed like I was able to create a new meteor project run `meteor add semantic:ui flemay:less-autoprefixer` and trigger the semantic build all with no problems. But when I tried to run the same command in an existing project. It would break the build.

again. take the above with a grin of salt, by no mean was I being systematic.

cheers.

**Comment by owenoak** [comment]
plus 1 for a 1.2 fix please!

**Comment by flemay** [comment]
@owenoak I am currently updating semantic:ui and once that is done I'll update this one. :)

**Comment by owenoak** [comment]
sweet, thank you sir!

**Comment by adam-paterson** [comment]
@flemay any idea when you're ready to ship the UI and this update?

**Comment by flemay** [comment]
@adam-paterson semantic:ui has been updated. Now I need to generate the error above.

**Comment by adam-paterson** [comment]
Oh excellent, you work quick @flemay.

**Comment by flemay** [comment]
Not so quick. Just happens I have time to put some effort atm :)

**Comment by adam-paterson** [comment]
Just realised, I was getting this error with the meteor-boilerplate project. I'm guessing because they require less implicitly in the package declaration.

meteor-boilerplate = Less 2.5.0_3
flemay/less-autoprefixer = 2.5.1

Not sure if any of that helps. I'm new to meteor

**Comment by flemay** [comment]
Can you try to remove `less` and add `flemay:less-autoprefixer`? :)

**Comment by adam-paterson** [comment]
**packages**
```
meteor-base

semantic:ui
flemay:less-autoprefixer
```

**result**
```
~/Projects/test • meteor --port 9999                                                                                                         8:30  adampaterson@Adams-MacBook-Pro
[[[[[ ~/Projects/test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:9999/```

**packages**
```
meteor-base

less
semantic:ui
flemay:less-autoprefixer
```

**result**
```
    Changes to your project's package version selections:
    
    caching-compiler  added, version 1.0.0
    less              added, version 2.5.0_3
    
    
    /Users/adampaterson/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
    						throw(ex);
    							  ^
    TypeError: Cannot call method 'displayName' of undefined
    	at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:141:64)
    	at /tools/isobuild/build-plugin.js:171:12
    	at Function._.each._.forEach (/Users/adampaterson/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    	at SourceProcessorSet.merge (/tools/isobuild/build-plugin.js:169:7)
    	at /tools/isobuild/compiler.js:368:26
    	at Array.forEach (native)
    	at /tools/isobuild/compiler.js:364:26
    	at /tools/utils/buildmessage.js:356:18
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at /tools/utils/buildmessage.js:349:34
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at /tools/utils/buildmessage.js:347:23
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    	at compileUnibuild (/tools/isobuild/compiler.js:360:16)
    	at /tools/isobuild/compiler.js:175:26
    	at Array.forEach (native)
    	at Function._.each._.forEach (/Users/adampaterson/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    	at Object.compile (/tools/isobuild/compiler.js:171:5)
    	at /tools/isobuild/bundler.js:2099:24
    	at /tools/utils/buildmessage.js:268:13
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at /tools/utils/buildmessage.js:261:29
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at /tools/utils/buildmessage.js:259:18
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at /tools/utils/buildmessage.js:250:23
    	at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    	at Object.capture (/tools/utils/buildmessage.js:249:19)
    	at Object.exports.bundle (/tools/isobuild/bundler.js:2047:31)
    	at /tools/runners/run-app.js:551:36
    	at time (/tools/tool-env/profile.js:232:28)
    	at Function.run (/tools/tool-env/profile.js:377:12)
    	at bundleApp (/tools/runners/run-app.js:541:34)
    	at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    	at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    	at /tools/runners/run-app.js:396:12
```

**Comment by flemay** [comment]
why there is still `less`?

**Comment by adam-paterson** [comment]
I added it to the package. Sorry my comment formatting was thrown out

**Comment by adam-paterson** [comment]
Without less, it works.

**Comment by flemay** [comment]
@nazarhussain do you have the package `less` in your app?

**Comment by nazarhussain** [comment]
@flemay  Yes it do contains `less` package in `.meteor/packages` file

**Comment by flemay** [comment]
I guess removing it will solve the issue.

**Comment by nazarhussain** [comment]
@flemay Yes removing the `less` package resolved the issue.

**Comment by flemay** [comment]
Cool! I still need to update to 1.2 but for now I will close this issue!

**Comment by nazarhussain** [comment]
@flemay  Thanks for taking actions on this issue.

**Comment by micahalcorn** [comment]
When I remove `less` the exception is silenced, but then my app has no styles. :/

**Comment by stevegrove** [comment]
I had to remove the package 'ecmascript' from the tutorial https://www.twilio.com/blog/2015/07/building-a-group-messaging-app-with-meteor-mongodb-and-twilio.html to get this to work with Meteor 1.3.2.4

'ecmascript' package has a dependency on 'less' which does not seem to work with meteor 1.3.2.4 for the reasons described above.
